# Generated by Django 5.0.7 on 2024-07-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prep_time', models.FloatField()),
                ('cook_time', models.FloatField()),
                ('total_time', models.FloatField()),
                ('servings', models.IntegerField()),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
            ],
        ),
    ]
